version: "3"

services:
  nginx:
    build: /home/olakhdar/Desktop/inception/srcs/requirements/nginx
    container_name: nginx
    restart: 'always'
    ports:
      - '443:443'
    volumes:
      - data:/var/www/html/
      - portfoliov:/var/www/html/portfolio
    networks:
        - internal
    depends_on:
      - wordpress
    init: true

  mariadb:
    container_name: mariadb
    build:
      context : /home/olakhdar/Desktop/inception/srcs/requirements/mariadb
      args:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_ROOT_PASSWORD
    restart: 'always'
    volumes: 
      - mariadbv:/var/lib/mysql/
    networks:
        - internal
    init: true

  wordpress:
    build: /home/olakhdar/Desktop/inception/srcs/requirements/wordpress
    container_name: wordpress
    restart: 'always'
    env_file: 
      - .env
    volumes: 
      - data:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - internal
    init: true

  redis:
    build: /home/olakhdar/Desktop/inception/srcs/requirements/bonus/redis
    container_name: redis
    restart: 'always'
    networks:
      - internal
    init: true
  
  ftp-server:
    build: //home/olakhdar/Desktop/inception/srcs/requirements/bonus/ftp-server
    container_name: ftp-server
    restart: 'always'
    volumes: 
      - data:/home/oussama/wordpress
    networks:
      - internal
    ports:
      - 21:21
      - "40000-40010:40000-40010"
    init: true

  adminer:
    build: /home/olakhdar/Desktop/inception/srcs/requirements/bonus/adminer
    container_name: adminer
    restart: 'always'
    networks:
        - internal
    init: true

  portfolio:
    build: /home/olakhdar/Desktop/inception/srcs/requirements/bonus/portfolio
    container_name: portfolio
    volumes: 
      - portfoliov:/var/www/html/portfolio
    networks:
      - internal
    init: true

  portainer:
    build: /home/olakhdar/Desktop/inception/srcs/requirements/bonus/portainer
    container_name: portainer
    restart: 'always'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerd:/data
    networks:
      - internal
    init: true

networks:
    internal:
      driver: bridge

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device:  /home/olakhdar/data/wordpress
      o: bind
  mariadbv:
    driver: local
    driver_opts:
      type: none
      device: /home/olakhdar/data/mariadb
      o: bind
  portfoliov:
    driver: local
    driver_opts:
      type: none
      device:  /home/olakhdar/data/portfoliov
      o: bind
  portainerd:
    driver: local
    driver_opts:
      type: none
      device: /home/olakhdar/data/portainer
      o: bind