version: "3"

services:
  nginx:
    build: /Users/olakhdar/Desktop/inception/srcs/requirements/nginx
    restart: 'always'
    ports:
      - '80:80'
    volumes: 
      - data:/var/www/html/
    networks:
        - internal
    depends_on:
      - wordpress

  mariadb:
    build: /Users/olakhdar/Desktop/inception/srcs/requirements/mariadb
    restart: 'always'
    volumes: 
      - "mariadbv:/var/lib/mysql"
    networks:
        - internal

  wordpress:
    build: /Users/olakhdar/Desktop/inception/srcs/requirements/wordpress
    restart: 'always'
    volumes: 
      - data:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - internal
  redis:
    build: /Users/olakhdar/Desktop/inception/srcs/requirements/bonus/redis
    restart: 'always'
    networks:
      - internal
  ftp-server:
    build: /Users/olakhdar/Desktop/inception/srcs/requirements/bonus/ftp-server
    restart: 'always'
    volumes: 
      - data:/home/oussama/wordpress
    networks:
      - internal
    ports:
      - 21:21
      - "40000-40010:40000-40010"

networks:
    internal:
      driver: bridge
volumes:
  data:
  mariadbv: